require(sonicLength)
set.seed(123)
chr <- sample(c(1:23,"X","Y"), 200, repl=TRUE )
pos <- sample(100000L,200)
strand <- sample(c("+","-"),200,repl=TRUE)
lens <- lapply(1:200, rfrag)
nlens <- sapply(lens, length)
loc.dframe <- data.frame( Chromosome=chr, Position=pos, Ort=strand )
len.dframe <- unique(cbind( loc.dframe[rep(1:200, nlens),], length=unlist(lens)))
rbind(head(len.dframe), tail(len.dframe)

id <- with(len.dframe, paste(Chromosome, Position, Ort))
id.counts <- table(factor(id,unique(id)))
plot(as.vector(nlens), as.vector(id.counts), xlab='number of sonicants',ylab='distinct lengths', xlim=c(1,100), ylim=c(1,100))
abline(a=0,b=1,col='gray')